name: Deploy DDL to BigQuery on Push

on:
  push:
    branches:
      - dev  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: mercadolibre-456701
          export_default_credentials: true 

      - name: Authenticate manually 
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project mercadolibre-456701

      - name: Run SQL in BigQuery
        run: |
          bq query \
            --use_legacy_sql=false \
            --project_id=mercadolibre-456701 \
            < DDL/create_tables.sql

      - name: Run DML scripts in BigQuery
              run: |
                for file in DML/*.sql; do
                  echo "Executing $file"
                  bq query \
                    --use_legacy_sql=false \
                    --project_id=mercadolibre-456701 \
                    < "$file"
                done
